# Generated by Django 5.1.7 on 2025-03-19 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='brands/'),
        ),
        migrations.CreateModel(
            name='Mower_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='models/')),
                ('model_name', models.CharField(default='', max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.brand')),
            ],
        ),
    ]
