# Generated by Django 5.1.7 on 2025-03-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_alter_brand_image_mower_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mower_model',
            name='model_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mower_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.mower_model')),
            ],
            options={
                'verbose_name': 'Lawnmower Model',
            },
        ),
    ]
