# Generated by Django 5.1.7 on 2025-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_alter_mower_model_model_name_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mower_model',
            options={'verbose_name': 'Lawnmower Model'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
