# Generated by Django 5.1.7 on 2025-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_alter_mower_model_options_alter_part_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='mower_model',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='part',
            name='mower_model',
            field=models.ManyToManyField(to='webstore.mower_model'),
        ),
    ]
