# Generated by Django 5.1.7 on 2025-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0005_remove_part_mower_model_alter_part_part_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Mower Part'},
        ),
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='parts/'),
        ),
    ]
