# Generated by Django 5.1.2 on 2025-03-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_alter_part_options_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_desc',
            field=models.CharField(default='No Description Available', max_length=200),
        ),
    ]
