# Generated by Django 5.1.2 on 2025-03-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0007_part_part_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_desc',
            new_name='description',
        ),
    ]
