# Generated by Django 5.1.2 on 2025-03-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0008_rename_part_desc_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
