# Generated by Django 5.1.2 on 2025-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0011_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='card',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='info',
            name='security_code',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
