# Generated by Django 5.1.2 on 2025-03-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0012_alter_info_card_alter_info_security_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Customer Info'},
        ),
    ]
