# Generated by Django 5.1.2 on 2025-03-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0013_alter_info_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Customer Info'},
        ),
    ]
