# Generated by Django 5.1.7 on 2025-03-29 21:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0014_alter_info_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='info',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='info',
            name='card',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='info',
            name='expiration',
            field=models.CharField(editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='info',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='webstore.order'),
        ),
        migrations.AlterField(
            model_name='info',
            name='security_code',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webstore.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='part',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='webstore.part'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
