# Generated by Django 5.1.7 on 2025-03-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0016_alter_info_email_alter_info_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
