# Generated by Django 5.1.7 on 2025-03-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0018_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='updated_at',
        ),
    ]
