# Generated by Django 5.1.7 on 2025-03-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0019_remove_usersession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Shipping Info'},
        ),
        migrations.AlterModelOptions(
            name='mower_model',
            options={'verbose_name': 'Lawnmower'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Part'},
        ),
        migrations.AlterField(
            model_name='info',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='webstore.order'),
        ),
    ]
