# Generated by Django 5.1.7 on 2025-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0020_alter_info_options_alter_mower_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='card',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='info',
            name='expiration',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='info',
            name='security_code',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
