# Generated by Django 5.1.7 on 2025-03-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0021_alter_info_card_alter_info_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='security_code',
            field=models.DecimalField(decimal_places=0, max_digits=3, max_length=3),
        ),
    ]
