# Generated by Django 5.1.7 on 2025-03-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0022_alter_info_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='security_code',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
