# Generated by Django 5.1.7 on 2025-03-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0023_alter_info_security_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='order',
            field=models.ForeignKey(blank=True, default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='webstore.order'),
        ),
    ]
