# Generated by Django 5.1.7 on 2025-03-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0025_alter_info_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='webstore.order'),
        ),
    ]
