# Generated by Django 5.1.7 on 2025-03-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0026_alter_info_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webstore.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.part'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
