# Generated by Django 5.2.7 on 2025-10-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0027_alter_orderitem_order_alter_orderitem_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webstore.order'),
        ),
    ]
